#!/usr/bin/env python3
"""Generate a poryscript-pls-compatible `.inc` of macro definitions from FE8's
`command_config.fe8.json`.

The Poryscript language server (huderlem/poryscript-pls, used by the
`karathan.poryscript` VS Code extension) learns the available scripting
*commands* by parsing the files listed in the
`languageServerPoryscript.commandIncludes` setting. It looks for blocks of the
form:

    .macro <command> <param0>, <param1>, ...
    .endm

and offers each `<command>` as a completion. By default it points at
pokeemerald's `asm/macros/event.inc` + `movement.inc`, which do not exist in
FE8. FE8's poryscript command set lives in `command_config.fe8.json` instead
(poryscript DSL name -> EAstdlib macro + positional args), so this script
translates that config into an `event.inc`-shaped file the LSP understands.

The macro *name* is the poryscript DSL command (e.g. `playbgm`), which is what
the user types in a `.pory` file -- NOT the underlying EAstdlib macro
(`MUSC`). The number of parameters matches the length of each command's `args`
array (commands with no `args` take zero parameters). The `call_command` is
also emitted, taking a single destination/label parameter.

Output is deterministic: commands are emitted in the order they appear in the
config's `commands` object (Python preserves JSON object insertion order), so
re-running yields a byte-identical file when the config is unchanged.

Usage:
    python3 vscode/generate_includes.py
        reads ./command_config.fe8.json (repo root), writes
        ./vscode/fe8_event_macros.inc

    python3 vscode/generate_includes.py --config PATH --output PATH
"""

import argparse
import json
import os
import re
import sys

# poryscript-pls discovers a command from a `.macro` block by capturing the
# name with `(\w+)`. A name with any character outside [A-Za-z0-9_] would be
# silently truncated by that capture (e.g. `warp-fast` -> `warp`), registering
# the wrong command. We require names to be fully `\w+` so the emitted name and
# the name the LSP sees are identical.
VALID_NAME_RE = re.compile(r"^\w+$")

# Resolve repo-root-relative defaults from this script's location so the
# generator works regardless of the current working directory.
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)
DEFAULT_CONFIG = os.path.join(REPO_ROOT, "command_config.fe8.json")
DEFAULT_OUTPUT = os.path.join(SCRIPT_DIR, "fe8_event_macros.inc")


def num_params(command):
    """Return the parameter count for a command config entry.

    A command's positional parameters are described by its `args` array (a
    list of indices into the underlying EAstdlib macro's arguments). The
    parameter count is simply the length of that array; commands without an
    `args` key take no parameters.
    """
    args = command.get("args")
    if args is None:
        return 0
    if not isinstance(args, list):
        raise ValueError(f"'args' must be a list, got {type(args).__name__}")
    return len(args)


def macro_block(name, param_count, doc=None):
    """Build a single `.macro ... .endm` block in event.inc style.

    Parameters are named `param0`, `param1`, ... and marked `:req` so the
    LSP's signature help shows them as required (matching how pokeemerald's
    event.inc marks positional macro args). A leading `@`-comment line
    documents the command, which poryscript-pls surfaces as hover/completion
    documentation.
    """
    lines = []
    if doc:
        lines.append(f"@ {doc}")
    params = ", ".join(f"param{i}:req" for i in range(param_count))
    if params:
        lines.append(f".macro {name} {params}")
    else:
        lines.append(f".macro {name}")
    lines.append(".endm")
    return "\n".join(lines)


def generate(config):
    """Render the full `.inc` text from a parsed config dict."""
    commands = config.get("commands")
    if not isinstance(commands, dict):
        raise ValueError("config is missing a 'commands' object")

    call_command = config.get("call_command")

    blocks = []
    blocks.append(
        "@ Auto-generated by vscode/generate_includes.py from "
        "command_config.fe8.json.\n"
        "@ Do NOT edit by hand. Regenerate when command_config.fe8.json "
        "changes.\n"
        "@ This file exists only to teach the Poryscript language server "
        "(poryscript-pls)\n"
        "@ the FE8 command set for autocomplete; it is not assembled."
    )

    emitted = set()
    for name, command in commands.items():
        if not isinstance(command, dict):
            raise ValueError(f"command '{name}' must be an object")
        if not VALID_NAME_RE.match(name):
            raise ValueError(
                f"command name '{name}' contains characters outside [A-Za-z0-9_]; "
                "the language server would truncate it. Rename it in "
                "command_config.fe8.json."
            )
        macro = command.get("macro", "?")
        doc = f"FE8 command '{name}' (EAstdlib macro {macro})."
        blocks.append(macro_block(name, num_params(command), doc))
        emitted.add(name)

    # Emit the call command (e.g. `call`), which jumps to a label/destination.
    # Skip it if a regular command already claimed that name, so we never emit
    # two `.macro <name>` blocks (which would register the command twice with
    # conflicting signatures).
    if call_command and call_command in emitted:
        print(
            f"note: call_command '{call_command}' is also a regular command; "
            "not emitting a duplicate macro",
            file=sys.stderr,
        )
        call_command = None
    if call_command:
        if not VALID_NAME_RE.match(call_command):
            raise ValueError(
                f"call_command '{call_command}' contains characters outside "
                "[A-Za-z0-9_]; the language server would truncate it."
            )
        call_macro = config.get("call_macro", "?")
        doc = (
            f"FE8 command '{call_command}' "
            f"(EAstdlib macro {call_macro}): call another event/label."
        )
        # One parameter: the destination label to call.
        block = []
        block.append(f"@ {doc}")
        block.append(f".macro {call_command} destination:req")
        block.append(".endm")
        blocks.append("\n".join(block))

    return "\n\n".join(blocks) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--config",
        default=DEFAULT_CONFIG,
        help="path to command_config.fe8.json (default: repo root)",
    )
    parser.add_argument(
        "--output",
        default=DEFAULT_OUTPUT,
        help="path to write the generated .inc (default: vscode/fe8_event_macros.inc)",
    )
    args = parser.parse_args(argv)

    try:
        with open(args.config, "r", encoding="utf-8") as f:
            config = json.load(f)
    except FileNotFoundError:
        print(f"error: config not found: {args.config}", file=sys.stderr)
        return 1
    except json.JSONDecodeError as e:
        print(f"error: invalid JSON in {args.config}: {e}", file=sys.stderr)
        return 1

    output = generate(config)

    with open(args.output, "w", encoding="utf-8") as f:
        f.write(output)

    num_macros = output.count("\n.macro ") + (1 if output.startswith(".macro ") else 0)
    print(f"wrote {args.output}: {num_macros} macro(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
